### ISSUE TITLE
编译遇到问题

### ISSUE THREAD

**Issue by graysondu** [FirmamentPilot/FMT_Firmware#5]
scons -j4
scons: Reading SConscript files ...
C:\env_released_1.2.0\env\tools\ConEmu\ConEmu\..\..\..\tools\gnu_gcc\arm_gcc\mingw\bin

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "E:\github\Firmament_Autopilot\FMT_Firmware\fmt_fmu\target\pixhawk\SConstruct", line 34, in <module>
cur dir:E:\github\Firmament_Autopilot\FMT_Firmware\fmt_fmu\src
scons: done reading SConscript files.

scons: warning: you do not seem to have the pywin32 extensions installed;
        parallel (-j) builds may not work reliably with open Python files.
File "C:\env_released_1.2.0\env\tools\Python27\Scripts\scons.py", line 204, in <module>
scons: Building targets ...
scons: building associated VariantDir targets: build
CC build\fmt\src\bsp.o
CC build\fmt\src\driver\buzzer\buzzer.o
CC build\fmt\src\driver\gpio\gpio.o
CC build\fmt\src\driver\gps\gps.o
CC build\fmt\src\driver\hmc5883\hmc5883.o
CC build\fmt\src\driver\hw_timer\drv_hwtimer.o
CC build\fmt\src\driver\i2c\i2c_soft.o
CC build\fmt\src\driver\l3gd20h\l3gd20h.o
CC build\fmt\src\driver\lidar\lidar.o
CC build\fmt\src\driver\lsm303d\lsm303d.o
CC build\fmt\src\driver\mpu6000\mpu6000.o
CC build\fmt\src\driver\ms5611\ms5611.o
CC build\fmt\src\driver\pwm\pwm_drv.o
CC build\fmt\src\driver\rtc\stm32f4_rtc.o
CC build\fmt\src\driver\sdio\sdio.o
CC build\fmt\src\driver\sdio\sd_dev.o
CC build\fmt\src\driver\spi\spi_drv.o
CC build\fmt\src\driver\stm32f4xx_it.o
CC build\fmt\src\driver\systick\systick_drv.o
CC build\fmt\src\driver\tca62724\tca62724.o
CC build\fmt\src\driver\usart\usart.o
CC build\fmt\src\driver\usb\src\usbd_cdc_core_loopback.o
CC build\fmt\src\driver\usb\src\usbd_core.o
CC build\fmt\src\driver\usb\src\usbd_desc.o
CC build\fmt\src\driver\usb\src\usbd_ioreq.o
CC build\fmt\src\driver\usb\src\usbd_req.o
CC build\fmt\src\driver\usb\src\usbd_usr.o
CC build\fmt\src\driver\usb\src\usb_bsp.o
CC build\fmt\src\driver\usb\src\usb_core.o
CC build\fmt\src\driver\usb\src\usb_dcd.o
CC build\fmt\src\driver\usb\src\usb_dcd_int.o
CC build\fmt\src\driver\utils\ringblk_buf.o
CC build\fmt\src\hal\accel\accel.o
CC build\fmt\src\hal\barometer\barometer.o
CC build\fmt\src\hal\fmtio_dev\fmtio_dev.o
CC build\fmt\src\hal\gyro\gyro.o
CC build\fmt\src\hal\i2c\i2c-bit-ops.o
CC build\fmt\src\hal\i2c\i2c_core.o
CC build\fmt\src\hal\i2c\i2c_dev.o
CC build\fmt\src\hal\mag\mag.o
CC build\fmt\src\hal\motor\motor.o
CC build\fmt\src\hal\pin\pin.o
CC build\fmt\src\hal\rc\rc.o
CC build\fmt\src\hal\serial\serial.o
CC build\fmt\src\hal\spi\spi_core.o
CC build\fmt\src\hal\spi\spi_dev.o
In file included from E:\github\Firmament_Autopilot\FMT_Firmware\fmt_fmu\include/firmament.h:21:0,
                 from E:\github\Firmament_Autopilot\FMT_Firmware\fmt_fmu\include/hal/serial.h:20,
                 from E:\github\Firmament_Autopilot\FMT_Firmware\fmt_fmu\src\hal\serial\serial.c:17:
E:\github\Firmament_Autopilot\FMT_Firmware\fmt_fmu\src\hal\serial\serial.c: In function '_serial_poll_rx':
E:\github\Firmament_Autopilot\FMT_Firmware\fmt_fmu\src\hal\serial\serial.c:33:27: error: expected identifier before '(' token

         ch = serial->ops->getc(serial);
                           ^
E:\github\Firmament_Autopilot\FMT_Firmware\fmt_fmu\src\hal\serial\serial.c: In function '_serial_poll_tx':
E:\github\Firmament_Autopilot\FMT_Firmware\fmt_fmu\src\hal\serial\serial.c:69:24: error: 'const struct usart_ops' has no member named '__sputc_r'
             serial->ops->putc(serial, '\r');
                        ^
E:\github\Firmament_Autopilot\FMT_Firmware\fmt_fmu\src\hal\serial\serial.c:72:20: error: 'const struct usart_ops' has no member named '__sputc_r'
         serial->ops->putc(serial, *data);
                    ^
E:\github\Firmament_Autopilot\FMT_Firmware\fmt_fmu\src\hal\serial\serial.c: In function '_serial_int_tx':
E:\github\Firmament_Autopilot\FMT_Firmware\fmt_fmu\src\hal\serial\serial.c:149:24: error: 'const struct usart_ops' has no member named '__sputc_r'
         if (serial->ops->putc(serial, *(char*)data) == -1) {
                        ^
In file included from E:\github\Firmament_Autopilot\FMT_Firmware\fmt_fmu\include/firmament.h:21:0,
                 from E:\github\Firmament_Autopilot\FMT_Firmware\fmt_fmu\include/hal/serial.h:20,
                 from E:\github\Firmament_Autopilot\FMT_Firmware\fmt_fmu\src\hal\serial\serial.c:17:
E:\github\Firmament_Autopilot\FMT_Firmware\fmt_fmu\src\hal\serial\serial.c: In function 'hal_serial_isr':
E:\github\Firmament_Autopilot\FMT_Firmware\fmt_fmu\src\hal\serial\serial.c:324:31: error: expected identifier before '(' token
             ch = serial->ops->getc(serial);
                               ^
scons: *** [build\fmt\src\hal\serial\serial.o] Error 1
scons: building terminated because of errors.

**Comment by JcZou** [comment]
你的compiler不对,如下
C:\env_released_1.2.0\env\tools\ConEmu\ConEmu......\tools\gnu_gcc\arm_gcc\mingw\bin

应该使用arm-none-eabi- toolchain ,参考：https://github.com/FirmamentPilot/fmt_user_guide_cn/blob/master/fmt_firmware/quick_start/quick_start.md进行配置

**Comment by graysondu** [comment]
> 你的compiler不对,如下
> C:\env_released_1.2.0\env\tools\ConEmu\ConEmu......\tools\gnu_gcc\arm_gcc\mingw\bin
> 
> 应该使用arm-none-eabi- toolchain ,参考：[https://github.com/FirmamentPilot/fmt_user_guide_cn/blob/master/fmt_firmware/quick_start/quick_start.md进行配置](https://github.com/FirmamentPilot/fmt_user_guide_cn/blob/master/fmt_firmware/quick_start/quick_start.md%E8%BF%9B%E8%A1%8C%E9%85%8D%E7%BD%AE)

感谢邹总，我再试试
